### ISSUE TITLE
devd -ol . returns error on Windows 7

### ISSUE THREAD

**Issue by rekna1** [cortesi/devd#25] opened 2015-11-11 22:59 UTC
I try to start devd following the example in the documentation but it always returns an error:

devd is in c:\tools and my files are in a different folder e.g. c:\projects\test

```
c:\tools\devd -ol .
```
returns the following error:
```
devd :error : could not watch routes for livereload: the syntax of the filename, foldername of volumename is incorrect
```
I am using version 0.2 (on windows 7 64bit)
When I specify the full pathname of the folder, it works.
```
c:\tools\devd -ol c:\projects\test
```

**Comment by cortesi** [comment] 2015-11-19 00:00
Hi there. I'm unable to reproduce this on Windows 10 - I'm hoping this means it's fixed in the latest release, rather than indicating some difference between Windows versions. Could you please try again with the latest release and re-open the ticket if the problem still exists?

**Comment by ngyuki** [comment] 2015-12-23 11:57
I have `devd-0.3` in windows 7.

```
$ devd --version
0.3
```

I try to start devd with watching dot directory, but returns error.

```
$ devd -ol .
devd: error: Could not watch routes for livereload: The filename, directory name, or volume label syntax is incorrect.
```

`-w` is also error.

```
$ devd -ow . .
devd: error: Could not watch path for livereload: The filename, directory name, or volume label syntax is incorrect.
```

When specified as '.\' then succeed.

```
$ devd -ol .\
20:54:42: Listening on http://devd.io (127.0.0.1:80)
20:54:43: GET /
  <- 200 OK 4.3kB
```

**Comment by jerryasher** [comment] 2016-01-17 19:09
I find the latest release, 0.3, has this problem on both Windows 7 64 as well as on Windows 10 64.
screenshot of it occurring on Windows 10 -> http://i.imgur.com/lAWbu3R.png

On Win 7, this occurs in both cmd.exe as well as using Cygwin's bash. On Windows 10, I don't have cygwin loaded, but it shows up in cmd.exe.

**Comment by cortesi** [comment] 2016-01-17 19:24
Hi folks. OK, lets dig into this a bit more. @jerryasher - out of curiosity, do you see the issue with powershell on Windows 10?

**Comment by jerryasher** [comment] 2016-01-17 19:48
Yeah, I do still see it even under powershell
http://i.imgur.com/jbRxYKV.png

**Comment by rekna1** [comment] 2016-01-19 07:15
An alternative is devd %cd% -ol
Seems to work everywhere

**Comment by jerryasher** [comment] 2016-01-19 21:25
> devd %cd% -ol

That does work in cmd, thanks, fwiw, it doesn't work in PowerShell.

**Comment by cortesi** [comment] 2016-03-22 01:19
Hi - I'm still unable to reproduce this on any of my test systems (Windows 10) - ``devd -l .`` and variations work perfectly for me. Could someone please confirm that this still doesn't work with the current master. If that's the case, I'll roll up my sleeves and get a test system running earlier versions of Windows up and running. 

Also, the thought occurs that this might be to do with the current working directory when running the command. If the error still occurs, could you please also show me the path for the directory you're serving.

**Comment by jerryasher** [comment] 2016-03-22 01:25
I just downloaded 0.4 and the problem has gone away for me.

**Comment by cortesi** [comment] 2016-03-22 01:26
OK, I'll close this issue for now. If anyone else is still seeing this, please re-open.

**Closed by cortesi** 2016-03-22 01:26 UTC
