### ISSUE TITLE
Go Get Install Fails with fatal error: 'CoreServices/CoreServices.h'

### ISSUE THREAD

**Issue by runeimp** [cortesi/devd#100] opened 2019-01-17 02:45 UTC
I tried installing _devd_ on a new MacBook Pro, just upgraded to Mojave 2 days ago. Go 1.11.4 has been installed since then as well. I've already `go get` installed a few apps with no problems. But when I try to install _devd_ (or _modd_) I get:

```bash
$ go get -u github.com/cortesi/devd/cmd/devd
# github.com/cortesi/devd/vendor/github.com/rjeczalik/notify
dev/lang/go/lib/src/github.com/cortesi/devd/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:10:10: fatal error: 'CoreServices/CoreServices.h' file not found
#include <CoreServices/CoreServices.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

I found `CoreServices.h` in several places

```
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Versions/A/Headers/CoreServices.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Versions/A/Headers/CoreServices.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h
```

I have Xcode 10.1 and command line tools all setup. But I'm not sure how to proceed to make this work.  :-(

**Comment by cortesi** [comment] 2019-01-17 03:19
Hi there. I'm afraid this doesn't seem like an issue related to devd - it looks like your local build environment is incomplete. I don't have a way to reproduce this exact issue, but I do see that there are some folks with similar issues and a resolution here:

https://github.com/ethereum/go-ethereum/issues/17940

Specifically, I think you need to install command-line tools after your upgrade. 

I'm closing this here since I don't believe it's devd-related.

**Closed by cortesi** 2019-01-17 03:19 UTC
